pipeline:
  n: 8
  population_size: 200
  selection_size: 20
  learning_method: "birkhoff"

run:
  generations: 100
  epsilon: 0.0001
  num_workers: null

pbil:
  learning_rate: 0.1
  mutation_rate: 0.01

birkhoff:
  alpha: 0.1

sinkhorn:
  iterations: 10

logging:
  gen_log_file: "generation_log.h5"   # Path where per-generation data will be written (HDF5)
